from fireclaw_core.llm_planner import LLMToolCallingPlanner
from fireclaw_core.planner import PlannerContext


class FakePlanningClient:
    def __init__(self, response):
        self.response = response
        self.requests = []

    def plan(self, request):
        self.requests.append(request)
        return self.response


def test_llm_tool_calling_planner_converts_valid_structured_response():
    client = FakePlanningClient(
        {
            "status": "planned",
            "message": "Generated by fake client.",
            "intent": "direct_skill_invocation",
            "target_floor": None,
            "steps": [{"skill_name": "echo_policy", "inputs": {"text": "二楼"}}],
        }
    )
    planner = LLMToolCallingPlanner(client=client)
    context = PlannerContext(
        session_id="session-a",
        turn_index=3,
        recent_records=[],
        skills=[{"name": "echo_policy"}],
    )

    result = planner.plan("运行 echo_policy 处理 二楼", context=context)

    assert result.status == "planned"
    assert result.intent == "direct_skill_invocation"
    assert result.plan.steps[0].skill_name == "echo_policy"
    assert result.plan.steps[0].inputs == {"text": "二楼"}


def test_llm_tool_calling_planner_sends_context_to_client():
    client = FakePlanningClient({"status": "clarify", "message": "Need more detail."})
    planner = LLMToolCallingPlanner(client=client)
    context = PlannerContext(
        session_id="session-a",
        turn_index=3,
        recent_records=[{"command": "救人", "status": "clarify"}],
        skills=[{"name": "navigate_to_floor"}],
    )

    planner.plan("二楼", context=context)

    assert client.requests[0]["command"] == "二楼"
    assert client.requests[0]["context"] == {
        "session_id": "session-a",
        "turn_index": 3,
        "recent_records": [{"command": "救人", "status": "clarify"}],
        "skills": [{"name": "navigate_to_floor"}],
    }
    assert client.requests[0]["tools"] == [
        {
            "type": "function",
            "function": {
                "name": "navigate_to_floor",
                "description": "No description provided.",
                "parameters": {
                    "type": "object",
                    "additionalProperties": True,
                },
            },
            "x-fireclaw": {
                "runtime": "unknown",
                "dry_run_only": True,
                "max_attempts": 1,
                "idempotent": False,
                "required_sensors": [],
                "failure_categories": [],
                "allow_real_robot": False,
                "timeout_seconds": None,
                "risk_level": "low",
            },
        }
    ]
    assert "response_schema" in client.requests[0]
    assert "instructions" in client.requests[0]


def test_llm_tool_calling_planner_falls_back_on_malformed_planned_response():
    client = FakePlanningClient(
        {
            "status": "planned",
            "message": "Malformed plan.",
            "intent": "rescue_victim",
            "steps": [{"inputs": {"floor": 2}}],
        }
    )
    planner = LLMToolCallingPlanner(client=client)
    context = PlannerContext(session_id="session-a", turn_index=1, recent_records=[], skills=[])

    result = planner.plan("去二楼救人", context=context)

    assert result.status == "planned"
    assert result.intent == "rescue_victim"
    assert result.target_floor == 2
    assert result.plan.steps[0].skill_name == "navigate_to_floor"
