"""FireClaw ROS Graph Discovery Probe and Topic Matching Heuristics."""
from __future__ import annotations

import http.client
import os
import socket
import xmlrpc.client
from dataclasses import dataclass, field
from typing import Any, Optional


class TimeoutTransport(xmlrpc.client.Transport):
    """XML-RPC transport with configurable socket timeout."""

    def __init__(self, timeout: float = 2.0, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.timeout = timeout

    def make_connection(self, host: Any) -> http.client.HTTPConnection:
        return http.client.HTTPConnection(host, timeout=self.timeout)


@dataclass
class DiscoveryReport:
    """Report generated by probing ROS Master and matching graph topics."""
    discovered: bool
    master_uri: str
    active_topics: list[tuple[str, str]] = field(default_factory=list)
    active_services: list[str] = field(default_factory=list)
    matched_topics: dict[str, str] = field(default_factory=dict)
    matched_actions: dict[str, str] = field(default_factory=dict)
    offline_fallback_recommendations: list[str] = field(default_factory=list)
    reason: Optional[str] = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "discovered": self.discovered,
            "master_uri": self.master_uri,
            "active_topics": [list(t) for t in self.active_topics],
            "active_services": list(self.active_services),
            "matched_topics": dict(self.matched_topics),
            "matched_actions": dict(self.matched_actions),
            "offline_fallback_recommendations": list(self.offline_fallback_recommendations),
            "reason": self.reason,
        }


class RosGraphDiscoverer:
    """Probes live ROS Graph or falls back to offline topic heuristics."""

    def probe_ros_master(
        self,
        master_uri: Optional[str] = None,
        timeout: float = 2.0,
    ) -> DiscoveryReport:
        target_uri = master_uri or os.environ.get("ROS_MASTER_URI", "http://localhost:11311")

        try:
            transport = TimeoutTransport(timeout=timeout)
            master = xmlrpc.client.ServerProxy(target_uri, transport=transport)

            # Query system state: [code, status, [pubs, subs, srvs]]
            state_resp = master.getSystemState("/fireclaw_discovery")
            if not isinstance(state_resp, (list, tuple)) or len(state_resp) < 3 or state_resp[0] != 1:
                raise RuntimeError(f"ROS Master getSystemState returned invalid status: {state_resp}")

            system_state = state_resp[2]
            services_raw = system_state[2] if len(system_state) > 2 else []
            active_services = [
                s[0] if isinstance(s, (list, tuple)) else str(s)
                for s in services_raw
            ]

            # Query topic types: [code, status, [[topic, type], ...]]
            types_resp = master.getTopicTypes("/fireclaw_discovery")
            if not isinstance(types_resp, (list, tuple)) or len(types_resp) < 3 or types_resp[0] != 1:
                raise RuntimeError(f"ROS Master getTopicTypes returned invalid status: {types_resp}")

            topic_types_raw = types_resp[2]
            active_topics: list[tuple[str, str]] = [
                (str(item[0]), str(item[1]))
                for item in topic_types_raw
                if isinstance(item, (list, tuple)) and len(item) >= 2
            ]

            matched_topics = self.match_topics(active_topics)
            matched_actions = {
                k: v for k, v in matched_topics.items() if k.endswith("_action")
            }

            return DiscoveryReport(
                discovered=True,
                master_uri=target_uri,
                active_topics=active_topics,
                active_services=active_services,
                matched_topics=matched_topics,
                matched_actions=matched_actions,
            )

        except (socket.error, OSError, TimeoutError, xmlrpc.client.Error, Exception) as exc:
            reason = f"ROS Master 连接失败 ({target_uri}): {exc}"
            recommendations = [
                f"当前无法连接到 ROS Master ({target_uri})，请确认 roscore 或 roslaunch 节点已启动",
                "若在真实机器人或远程机上运行，请检查 ROS_MASTER_URI 与 ROS_IP 环境变量配置",
                "若在 Gazebo 仿真环境中，可先使用型号默认配置：激光雷达 [/scan]，里程计 [/odom]，速度控制 [/cmd_vel]",
                "离线模式下系统将自动载入内置型号推荐 Topic 列表进行预填",
            ]
            return DiscoveryReport(
                discovered=False,
                master_uri=target_uri,
                reason=reason,
                offline_fallback_recommendations=recommendations,
            )

    def match_topics(self, active_topics: list[tuple[str, str]]) -> dict[str, str]:
        """Matches active ROS topics against FireClaw sensor/actuator semantic slots."""
        matched: dict[str, str] = {}

        for topic, msg_type in active_topics:
            t_lower = topic.lower()
            m_lower = msg_type.lower()

            # 1. Action server detection (e.g. /move_base/goal -> /move_base)
            if t_lower.endswith("/goal") and "action" in m_lower or "move_base" in t_lower:
                action_base = topic.rsplit("/", 1)[0]
                matched["navigation_action"] = action_base

            # 2. Laser Scan
            if "laser_scan_topic" not in matched:
                if msg_type == "sensor_msgs/LaserScan" or "scan" in t_lower or "lidar" in t_lower:
                    matched["laser_scan_topic"] = topic

            # 3. Odometry
            if "odometry_topic" not in matched:
                if msg_type == "nav_msgs/Odometry" or "odom" in t_lower:
                    matched["odometry_topic"] = topic

            # 4. Cmd Vel
            if "cmd_vel_topic" not in matched:
                if msg_type == "geometry_msgs/Twist" or "cmd_vel" in t_lower or "velocity" in t_lower:
                    matched["cmd_vel_topic"] = topic

            # 5. Thermal Camera (Image with thermal / ir in name)
            if "thermal_camera_topic" not in matched:
                if ("image" in m_lower or "compressedimage" in m_lower) and any(
                    k in t_lower for k in ("thermal", "ir", "flir", "infrared")
                ):
                    matched["thermal_camera_topic"] = topic

            # 6. RGB Camera (Image without thermal keywords)
            if "rgb_camera_topic" not in matched:
                if ("image" in m_lower or "compressedimage" in m_lower) and not any(
                    k in t_lower for k in ("thermal", "ir", "flir", "infrared")
                ):
                    if any(k in t_lower for k in ("camera", "rgb", "color", "image")):
                        matched["rgb_camera_topic"] = topic

            # 7. Gas Sensor
            if "gas_sensor_topic" not in matched:
                if "float" in m_lower or "gas" in t_lower or "air_quality" in t_lower:
                    if any(k in t_lower for k in ("gas", "air", "sensor", "detector")):
                        matched["gas_sensor_topic"] = topic

            # 8. Gimbal Command
            if "gimbal_cmd_topic" not in matched:
                if "gimbal" in t_lower:
                    matched["gimbal_cmd_topic"] = topic

            # 9. Water Cannon
            if "water_cannon_topic" not in matched:
                if "water_cannon" in t_lower or "cannon" in t_lower:
                    matched["water_cannon_topic"] = topic

            # 10. IMU
            if "imu_topic" not in matched:
                if msg_type == "sensor_msgs/Imu" or "imu" in t_lower:
                    matched["imu_topic"] = topic

            # 11. PointCloud
            if "pointcloud_topic" not in matched:
                if msg_type == "sensor_msgs/PointCloud2" or "cloud" in t_lower or "points" in t_lower:
                    matched["pointcloud_topic"] = topic

        return matched
